### ISSUE TITLE
simplify by adding -auth to `create job`

### ISSUE THREAD

**Issue by kjk** [fuzzitdev/fuzzit#10]
Currently to create a job, one has to do:
```
./fuzzit auth ${FUZZIT_API_KEY}
export TARGET_ID=2n6hO2dQzylLxX5GGhRG
./fuzzit create job --type $1 --branch $TRAVIS_BRANCH --revision $TRAVIS_COMMIT $TARGET_ID ./fuzzer
```

It could be simplified to:
```
./fuzzit create job --auth ${FUZZIT_API_KEY} --type $1 --branch $TRAVIS_BRANCH --revision $TRAVIS_COMMIT $TARGET_ID ./fuzzer
```
or:
```
./fuzzit create job --api-key ${FUZZIT_API_KEY} --type $1 --branch $TRAVIS_BRANCH --revision $TRAVIS_COMMIT $TARGET_ID ./fuzzer
```

**Comment by yevgenypats** [comment]
but the ./fuzzit auth is only needed once and not before every `create job`. Do you still think this will be more convenient?

**Comment by kjk** [comment]
I'm thinking one step is better than two. 

Less docs to write, less things to get wrong when user copy & pastes the commands.

On a CI system things start from scratch, so the caching doesn't happen anyway.

**Comment by yevgenypats** [comment]
This is now solved via `--api-key` that can be either passed as a flag or as an environment variable `FUZZIT_API_KEY`
