### ISSUE TITLE
Make a homebrew formula for fuzzit

### ISSUE THREAD

**Issue by kjk** [fuzzitdev/fuzzit#16]
On Mac, people are most used to using homebrew (https://brew.sh/) to install binaries.

`fuzzit` should be installable via homebrew as `brew install fuzzit`.

I've never done it myself, but adding a formula is just writing a simple ruby build script and creating a PR. An example formula for a Go program: https://github.com/Homebrew/homebrew-core/blob/master/Formula/caddy.rb

(it's more complicated than most because of the config, but it's one I know is written in Go)

**Comment by yevgenypats** [comment]
I've added homebrew tap (also added to the README.)

`brew install fuzzitdev/tap/fuzzit`
