### ISSUE TITLE
Target still created if invalid `--seed` argument

### ISSUE THREAD

**Issue by kjk** [fuzzitdev/fuzzit#19]
```
# fuzzit create target promql --seed corups.tar.gz2
2019/08/05 17:38:10 Creating target...
2019/08/05 17:38:11 open corups.tar.gz2: no such file or directory
```

This still created a target on the backend. Should validate the file name first and maybe add code to delete target on the backend if something along the way fails.

**Comment by yevgenypats** [comment]
This is fixed in master. will do a release soon.

**Comment by yevgenypats** [comment]
fixed in this released. https://github.com/fuzzitdev/fuzzit/releases/tag/v2.4.0
