### ISSUE TITLE
web ui: be able to tell if target has (initial) corpus

### ISSUE THREAD

**Issue by kjk** [fuzzitdev/fuzzit#20]
For the lack of a better place to report issues for web ui, I'm putting it here.

In target settings (e.g. https://app.fuzzit.dev/orgs/kkowalczyk/targets/6tjvhFDeG1Mh4bSyQZzH) I would like to be able to tell from UI if initial corpus has been uploaded.

Currently, the only way is to click on the download button and it'll either show a message that there is no corpus or start the download.

**Comment by yevgenypats** [comment]
fixed.
