### ISSUE TITLE
add --if-not-exists option to fuzzit create target

### ISSUE THREAD

**Issue by kjk** [fuzzitdev/fuzzit#25]
In integration scripts I'm doing: `./fuzzit create target ${TARGET} || true`

This is to make the script continue if it fails because the target already exists.

Unfortunately it suppresses all other errors (e.g. failure to authenticate).

Would be good to have `--if-not-exists` option which would do nothing and return success if target already exists.

**Comment by yevgenypats** [comment]
I'm not sure I agree that a target should be created as part of the CI script.
Target should be created only once (and possibly configured either via the CLI or the UI).
What runs in the CI should be only those actions that are needed to run every push/PR.

**Comment by kjk** [comment]
I understand that position.

However, not doing that from the script makes our job of preparing scripts for projects harder because it requires more steps from them and more explanations from us.

To simplify things, even more, we could remove "create target" from cli and have it be implicit in "create job".

Since the only way to upload fuzzing job is from cli, we could get rid of the "Create Target" flow in the UI.

**Comment by kjk** [comment]
Well, the wrinkle is the -seed option, so maybe we do need `create target`

**Comment by yevgenypats** [comment]
I get your idea though for me the "seamless" target creation is more confusing. Though maybe it is just me. let's keep this issue open for now and see if more people have a need for this feature.

**Comment by yevgenypats** [comment]
Ok added. here is also the use-case for reference

https://github.com/envoyproxy/envoy/pull/7509#discussion_r317279006
