### ISSUE TITLE
Add "magic" mode for Go projects

### ISSUE THREAD

**Issue by kjk** [fuzzitdev/fuzzit#26]
Currently adding integration to a Go project requires writing a multi-step shell script.

Wouldn't it be nice if we could just do: `fuzzit gomagic --org=kkowalczyk --fuzzing` (or `fuzzit gomagic --regression`) and `fuzzit` just does the right thing?

(`gomagic` is just a placeholder name).

For most projects it would be possible to automate everything with heuristics.

It's not a replacement, just an addition (the old way would still work).

Roughly what this would do:
* for `--fuzzing` check api key is provided via FUZZIT_API_KEY or --auth option an exit with error message if not
* auto-detect fuzz targets by parsing code and looking for packages with `gofuzz` tag
* auto-detect corpus following some rules (e.g. it must be a "corpus" directory)
* install `go-fuzz` and build targets (with auto-naming of targets based on ${package}-${func}
* build fuzzing targets with `clang`
* create targets if not exist on the server
* upload jobs
* get git branch and commit from the repo
etc.

The logic might grow to accommodate more complex scenarios but it could start with just simple scenarios like a single fuzz target.

It should log all the steps so that people understand what it does.

**Comment by kjk** [comment]
Initially, we could punt on the hardest problem of auto-detecting fuzz targets AND cleanly support multi-target scenarios by adding `.fuzzit.yml` config (kind of like fuzzbuzz).

The config would list go fuzzing targets:
* target name
* package
* fuzzing function (optional, if more than one per package)
* seed corpus (optional)

As a bonus `.fuzzit.yml` would be an advertisement for the service.

The rest of the heuristics is simple.

**Comment by yevgenypats** [comment]
Some steps here are easy to automate and some steps are much harder (to make them work in the general case). Let's put it here and see what we think after we gain more experience with go projects.

**Comment by yevgenypats** [comment]
moving this to internal trello. as well as some steps here are already done.
