### ISSUE TITLE
plain text alert emails

### ISSUE THREAD

**Issue by miekg** [fuzzitdev/fuzzit#29]
The current alert email are html formatted, but somewhat weird, my `mutt` converts this to
~~~
[-- Autoview using /usr/bin/w3m -I 'UTF-8' -dump -T text/html '/home/miek/tmp/mutt.html' --]
A crash was introduced in rewrite

---------
You can unsubscribe from these alerts via the dashboard
~~~
And doesn't actually render any links.

*anyway* it would be nice to have the option to just receive plain text emails.

**Comment by yevgenypats** [comment]
I can add this option though then there will be no links (at least not clickable). I would prefer it though just to work.
I made some change to the html (this is the simplest html with single <a> tag), It should work now. can rerun it in a new target and see if the email is now well formatted?

**Comment by yevgenypats** [comment]
@miekg do you know if this was fixed. Do you still receive broken emails?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [fuzzitdev/fuzzit] plain text a..." ]
>@miekg do you know if this was fixed. Do you still receive broken emails?

I think that worked better. But I had to disable fuzzing, because of the go 
module stuff just not working. Things stopped compiling

**Comment by yevgenypats** [comment]
ok got it. I'll keep an eye on the go modules support. We can wait a week or so and if it doesn't get in we can use [fuzzitdev/go-fuzz ](https://github.com/fuzzitdev/go-fuzz) fork that support go modules till it will be upstreamed. let me know if this is something you need/want.

closing the issue for now as it seems that the issue was fixed.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [fuzzitdev/fuzzit] plain text a..." ]
>ok got it. I'll keep an eye on the go modules support. We can wait a week or so and if it doesn't get in we can use [fuzzitdev/go-fuzz ](https://github.com/fuzzitdev/go-fuzz) fork that support go modules till it will be upstreamed. let me know if this is something you need/want.
>
>closing the issue for now as it seems that the issue was fixed.

I can wait for it to land in proper upstream. 

Thanks for your work on this.
