### ISSUE TITLE
Idea: a public status page for open source projects

### ISSUE THREAD

**Issue by mvdan** [fuzzitdev/fuzzit#34]
Right now, when one clicks on the fuzzit markdown badge, the link goes to the dashboard that's only accessible by the owner. That's not very good.

I think it should be a different page than the dashboard, as the dashboard shows way too much sensitive information. For example, if a crash was found in the past 24h and hasn't been fixed and released yet, that could be used by bad actors to try to break services.

Perhaps a status very much like a static page would be better; think kinda like https://www.githubstatus.com/. It could contain harmless information about the past 30 days or whatever period of time we decide:

* N cpu-hours spent fuzzing in the past N days
* N fixed crashes in the past N days (not counting unfixed!)
* N times that the public corpus was downloaded in the past N days
* N times that regression tests were run in the past N days
* Stats on the public corpus (size, how much it grew in the past N days)

**Comment by yevgenypats** [comment]
moved to internal task list
