### ISSUE TITLE
idea for automated test

### ISSUE THREAD

**Issue by kjk** [fuzzitdev/fuzzit#7]
Regarding automated testing, https://github.com/fuzzitdev/fuzzit/issues/3 could be caught with the following setup, which can be thought as integration (as opposed to unit) test for fuzzit:

* create a repository like `go-example` (e.g. `fuzzit-tester`)
* setup it up on travis CI with:
  * daily cron so that it gets re-executed daily
  * in `ci/fuzzit.sh` script, instead of downloading release build, builds `fuzzit` executable from master

This way once a day latest `fuzzit` code will be tested in an end-to-end fashion. If `fuzzit` fails like in https://github.com/fuzzitdev/fuzzit/issues/3, it'll be reported by CI system on `fuzzit-tester` repo.

**Comment by yevgenypats** [comment]
Agree. I'll add this to `example-go` soon.

**Comment by yevgenypats** [comment]
Moving to internal task mgmt as this is used for more public-facing features.
